### ISSUE TITLE
List not always correct.

### ISSUE THREAD

**Issue by Naladdar** [germanoid/germanoid.github.io#1]
First, thank you for this helper. I use it pretty often.

I found a word he dont recognice as correct it seems (see attached pictures)

Growth=0, Wooden=0 and Choose=1, but he dont accept Choose as a valid answer.

![helper01](https://user-images.githubusercontent.com/10608926/50007489-672b8600-ffb1-11e8-8890-2c8ebdf90200.png)
![helper02](https://user-images.githubusercontent.com/10608926/50007498-6b57a380-ffb1-11e8-8e28-ec470146985d.png)

**Comment by germanoid** [comment]
I am pretty sure the password is SEWAGE.
In your screenshot you see clearly: CHOOSE is not the right word. I don't see a problem here.

**Comment by Naladdar** [comment]
Thank you for the answer :-) After thinking further i see my error. Thanks alot for taking your time to read my issues.
